# Generated by Django 4.0.4 on 2022-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[(8, 'jazz'), (2, 'metal'), (7, 'rap'), (5, 'muzyka akustyczna'), (0, 'inne'), (6, 'muzyka elektroniczna'), (3, 'pop'), (1, 'rock'), (4, 'reggae')], default=0, max_length=2),
        ),
    ]
