# Generated by Django 4.0.4 on 2022-05-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0002_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[(2, 'metal'), (3, 'pop'), (5, 'muzyka akustyczna'), (1, 'rock'), (8, 'jazz'), (0, 'inne'), (7, 'rap'), (6, 'muzyka elektroniczna'), (4, 'reggae')], default=0, max_length=2),
        ),
    ]
