# Generated by Django 4.0.4 on 2022-05-30 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage_online', '0003_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='user',
            field=models.ManyToManyField(related_name='bands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[(1, 'rock'), (0, 'inne'), (6, 'muzyka elektroniczna'), (3, 'pop'), (5, 'muzyka akustyczna'), (2, 'metal'), (4, 'reggae'), (7, 'rap'), (8, 'jazz')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bands_photos'),
        ),
    ]
