# Generated by Django 4.0.4 on 2022-05-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0007_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inne'), (8, 'jazz'), (3, 'pop'), (6, 'muzyka elektroniczna'), (5, 'muzyka akustyczna'), (1, 'rock'), (2, 'metal'), (7, 'rap'), (4, 'reggae')], default=0),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(upload_to='bands_photos'),
        ),
    ]
