# Generated by Django 4.0.4 on 2022-05-31 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0008_alter_band_genre_alter_band_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='add_2db_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inne'), (7, 'rap'), (6, 'muzyka elektroniczna'), (4, 'reggae'), (1, 'rock'), (8, 'jazz'), (3, 'pop'), (5, 'muzyka akustyczna'), (2, 'metal')], default=0),
        ),
    ]
