# Generated by Django 4.0.4 on 2022-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0009_band_add_2db_date_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='show_contact_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(8, 'jazz'), (2, 'metal'), (1, 'rock'), (4, 'reggae'), (5, 'muzyka akustyczna'), (7, 'rap'), (3, 'pop'), (0, 'inne'), (6, 'muzyka elektroniczna')], default=0),
        ),
    ]
