# Generated by Django 4.0.4 on 2022-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0010_band_contact_email_band_show_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(6, 'muzyka elektroniczna'), (1, 'rock'), (0, 'inne'), (7, 'rap'), (3, 'pop'), (5, 'muzyka akustyczna'), (4, 'reggae'), (2, 'metal'), (8, 'jazz')], default=0),
        ),
    ]
