# Generated by Django 4.0.4 on 2022-06-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0011_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inne'), (4, 'reggae'), (5, 'muzyka akustyczna'), (3, 'pop'), (8, 'jazz'), (2, 'metal'), (7, 'rap'), (1, 'rock'), (6, 'muzyka elektroniczna')], default=0),
        ),
    ]
