# Generated by Django 4.0.4 on 2022-06-03 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0013_song_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='garage_online.band'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'rock'), (4, 'reggae'), (0, 'inne'), (6, 'muzyka elektroniczna'), (8, 'jazz'), (7, 'rap'), (5, 'muzyka akustyczna'), (2, 'metal'), (3, 'pop')], default=0),
        ),
    ]
