# Generated by Django 4.0.4 on 2022-06-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0014_song_band_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(6, 'muzyka elektroniczna'), (2, 'metal'), (5, 'muzyka akustyczna'), (0, 'inne'), (7, 'rap'), (4, 'reggae'), (3, 'pop'), (1, 'rock'), (8, 'jazz')], default=0),
        ),
    ]
