# Generated by Django 4.0.4 on 2022-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0016_alter_band_genre_alter_song_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(4, 'reggae'), (3, 'pop'), (2, 'metal'), (1, 'rock'), (6, 'muzyka elektroniczna'), (0, 'inne'), (8, 'jazz'), (5, 'muzyka akustyczna'), (7, 'rap')], default=0),
        ),
    ]
