# Generated by Django 4.0.4 on 2022-06-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0018_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inne'), (7, 'rap'), (5, 'muzyka akustyczna'), (2, 'metal'), (6, 'muzyka elektroniczna'), (3, 'pop'), (8, 'jazz'), (4, 'reggae'), (1, 'rock')], default=0),
        ),
    ]
