# Generated by Django 4.0.4 on 2022-06-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0019_alter_band_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'inne'), (6, 'muzyka elektroniczna'), (5, 'muzyka akustyczna'), (8, 'jazz'), (1, 'rock'), (2, 'metal'), (7, 'rap'), (4, 'reggae'), (3, 'pop')], default=0),
        ),
    ]
