# Generated by Django 4.0.4 on 2022-06-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0021_sociallinks_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='band',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='garage_online.band'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(7, 'rap'), (4, 'reggae'), (8, 'jazz'), (1, 'rock'), (0, 'inne'), (5, 'muzyka akustyczna'), (6, 'muzyka elektroniczna'), (3, 'pop'), (2, 'metal')], default=0),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='name',
            field=models.CharField(choices=[(5, 'iTuens'), (3, 'YouTube'), (6, 'Instagram'), (2, 'Spotify'), (0, 'Facebook'), (1, 'Bandcamp'), (7, 'inne'), (4, 'SoundCloud')], max_length=20),
        ),
    ]
