# Generated by Django 4.0.4 on 2022-06-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0022_sociallinks_band_alter_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(7, 'inne'), (4, 'SoundCloud'), (0, 'Facebook'), (2, 'Spotify'), (3, 'YouTube'), (1, 'Bandcamp'), (6, 'Instagram'), (5, 'iTuens')], max_length=20)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'pop'), (0, 'inne'), (4, 'reggae'), (5, 'muzyka akustyczna'), (6, 'muzyka elektroniczna'), (8, 'jazz'), (1, 'rock'), (7, 'rap'), (2, 'metal')], default=0),
        ),
        migrations.DeleteModel(
            name='SocialLinks',
        ),
        migrations.AddField(
            model_name='sociallink',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage_online.band'),
        ),
    ]
