# Generated by Django 4.0.4 on 2022-06-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0023_sociallink_alter_band_genre_delete_sociallinks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(6, 'muzyka elektroniczna'), (7, 'rap'), (2, 'metal'), (4, 'reggae'), (3, 'pop'), (0, 'inne'), (1, 'rock'), (8, 'jazz'), (5, 'muzyka akustyczna')], default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(choices=[(4, 'SoundCloud'), (2, 'Spotify'), (0, 'Facebook'), (6, 'Instagram'), (3, 'YouTube'), (5, 'iTuens'), (1, 'Bandcamp'), (7, 'inne')], max_length=20),
        ),
    ]
