# Generated by Django 4.0.4 on 2022-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0024_alter_band_genre_alter_sociallink_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'pop'), (4, 'reggae'), (8, 'jazz'), (2, 'metal'), (7, 'rap'), (5, 'muzyka akustyczna'), (1, 'rock'), (0, 'inne'), (6, 'muzyka elektroniczna')], default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.SmallIntegerField(choices=[(7, 'inne'), (5, 'iTuens'), (0, 'Facebook'), (6, 'Instagram'), (3, 'YouTube'), (4, 'SoundCloud'), (1, 'Bandcamp'), (2, 'Spotify')], max_length=2),
        ),
    ]
