# Generated by Django 4.0.4 on 2022-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0025_alter_band_genre_alter_sociallink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(5, 'muzyka akustyczna'), (4, 'reggae'), (1, 'rock'), (7, 'rap'), (8, 'jazz'), (0, 'inne'), (3, 'pop'), (2, 'metal'), (6, 'muzyka elektroniczna')], default=0),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.SmallIntegerField(choices=[(6, 'Instagram'), (1, 'Bandcamp'), (4, 'SoundCloud'), (5, 'iTuens'), (3, 'YouTube'), (0, 'Facebook'), (7, 'inne'), (2, 'Spotify')]),
        ),
    ]
