# Generated by Django 4.0.4 on 2022-06-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0028_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='main_song',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'other'), (1, 'acoustic'), (2, 'alternative'), (3, 'ambient'), (4, 'blues'), (5, 'classical'), (6, 'country'), (7, 'devotional'), (8, 'electronic'), (9, 'experimental'), (10, 'folk'), (11, 'funk'), (12, 'jazz'), (13, 'latin'), (14, 'metal'), (15, 'pop'), (16, 'punk'), (17, 'R&B/soul'), (18, 'rap'), (19, 'rap - instrumental beat'), (20, 'reggae'), (21, 'rock'), (22, 'soundtrack'), (23, 'world')], default=0),
        ),
    ]
