# Generated by Django 4.0.4 on 2022-06-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0030_alter_band_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
