# Generated by Django 4.0.4 on 2022-07-02 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage_online', '0032_alter_band_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalColorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#fcba03', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
