# Generated by Django 4.0.4 on 2022-07-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0034_globalcolorset_background_light_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(upload_to='media/bands_photos'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='media/songs'),
        ),
    ]
