# Generated by Django 4.0.4 on 2022-07-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0037_alter_band_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='band',
            name='image',
            field=models.ImageField(null=True, upload_to='bands_photos'),
        ),
    ]
