# Generated by Django 4.0.4 on 2022-07-26 10:01

from django.db import migrations, models
import garage_online.models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0038_alter_band_city_alter_band_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcolorset',
            name='primary_color',
            field=models.CharField(default='#b5a578', max_length=7),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to=garage_online.models.refactor_song_dir),
        ),
    ]
