# Generated by Django 4.0.4 on 2022-07-09 07:59

from django.db import migrations, models
import garage_online.utils


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0038_alter_band_city_alter_band_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to=garage_online.utils.refactor_song_dir),
        ),
    ]
