# Generated by Django 4.0.4 on 2022-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_online', '0039_alter_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcolorset',
            name='primary_color',
            field=models.CharField(default='#b5a578', max_length=7),
        ),
    ]
